create table AP_GROUP_PERSON
(
    MY_ID      integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)   not null,
    MY_VARCHAR      varchar(15)  null
 constraint CKC_MY_VARCHAR check (MY_VARCHAR in ('A','B')),
    MY_TIMESTAMP      timestamp default now  null
);

